services:

    #
    # Object Managers
    #
    elcodi.object_manager.image:
        parent: elcodi.abstract_manager
        arguments:
            - %elcodi.entity.image.class%

    elcodi.object_manager.attachment:
        parent: elcodi.abstract_manager
        arguments:
            - %elcodi.entity.attachment.class%
