services:

    #
    # Repositories
    #

    #
    # Repository for entity image
    #
    elcodi.repository.image:
        parent: elcodi.abstract_repository
        arguments:
            - %elcodi.entity.image.class%

    elcodi.repository.attachment:
        parent: elcodi.abstract_repository
        arguments:
            - %elcodi.entity.attachment.class%
