Elcodi\Component\Product\Entity\Category:
    type: entity
    repositoryClass: Elcodi\Component\Product\Repository\CategoryRepository
    table: category
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        name:
            column: name
            type: string
            length: 255
            nullable: false
        slug:
            column: slug
            type: string
            length: 255
            nullable: false
        root:
            column: root
            type: boolean
            nullable: false
        position:
            column: position
            type: integer
            nullable: false
        cssClass:
            column: css_class
            type: string
            length: 255
            nullable: true
        metaTitle:
            column: meta_title
            type: string
            length: 255
            nullable: true
        metaDescription:
            column: meta_description
            type: string
            length: 255
            nullable: true
        metaKeywords:
            column: meta_keywords
            type: string
            length: 255
            nullable: true
        imagesSort:
            column: images_sort
            type: string
            length: 2048
            nullable: true
        createdAt:
            column: created_at
            type: datetime
        updatedAt:
            column: updated_at
            type: datetime
        enabled:
            column: enabled
            type: boolean
        extraData:
            column: extra_data
            type: json_array
            nullable: true
        showInHome:
            column: show_in_home
            type: boolean
            options:
                default: false

    oneToMany:
        subCategories:
            targetEntity: Elcodi\Component\Product\Entity\Interfaces\CategoryInterface
            mappedBy: parent

    manyToOne:
        parent:
            targetEntity: Elcodi\Component\Product\Entity\Interfaces\CategoryInterface
            inversedBy: subCategories
            joinColumn:
                name: parent_id
                referencedColumnName: id
                nullable: true
                onDelete: "SET NULL"
                onUpdate: "CASCADE"
        principalImage:
            targetEntity: Elcodi\Component\Media\Entity\Interfaces\ImageInterface
            joinColumn:
                onDelete: SET NULL
                name: principal_image_id
                referencedColumnName: id
                nullable: true
                
    manyToMany:
        purchasables:
            targetEntity: Elcodi\Component\Product\Entity\Interfaces\PurchasableInterface
            mappedBy: categories
        images:
            targetEntity: Elcodi\Component\Media\Entity\Interfaces\ImageInterface
            joinTable:
                name: category_image
                joinColumns:
                    category_id:
                        referencedColumnName: id
                        onDelete: "CASCADE"
                inverseJoinColumns:
                    image_id:
                        referencedColumnName: id
                        onDelete: "CASCADE"
        icons:
            targetEntity: Elcodi\Component\Media\Entity\Interfaces\ImageInterface
            joinTable:
                name: category_icons
                joinColumns:
                    category_id:
                        referencedColumnName: id
                        onDelete: "CASCADE"
                inverseJoinColumns:
                    image_id:
                        referencedColumnName: id
                        onDelete: "CASCADE"

    lifecycleCallbacks:
        preUpdate: [loadUpdateAt]
        prePersist: [loadUpdateAt]
