Elcodi\Component\Product\Entity\Pack:
    type: entity
    repositoryClass: Elcodi\Component\Product\Repository\PackRepository
    table: pack

    fields:
        stockType:
            column: stock_type
            type: integer
            nullable: false
        type:
            column: type
            type: integer
            nullable: true
        discount:
            column: discount
            type: integer


    manyToMany:
        purchasables:
            targetEntity: Elcodi\Component\Product\Entity\Interfaces\PurchasableInterface
            joinTable:
                name: pack_purchasable
                joinColumns:
                    pack_id:
                        referencedColumnName: id
                        onDelete: "CASCADE"
                inverseJoinColumns:
                    purchasable_id:
                        referencedColumnName: id
                        onDelete: "CASCADE"
