services:
    elcodi.repository.address:
        parent: elcodi.abstract_repository
        arguments:
            - %elcodi.entity.address.class%

    elcodi.repository.location:
        parent: elcodi.abstract_repository
        arguments:
            - %elcodi.entity.location.class%

    elcodi.repository.country:
        parent: elcodi.abstract_repository
        arguments:
            - %elcodi.entity.country.class%
