services:

    #
    # Related Purchasables Provider Adapters
    #
    elcodi.related_purchasables_provider.same_category:
        class: Elcodi\Component\Product\Adapter\SimilarPurchasablesProvider\SameCategoryRelatedPurchasableProvider
        arguments:
            - '@elcodi.repository.purchasable'
            - '@?security.token_storage'
