services:

    #
    # Services
    #
    elcodi.manager.password:
        class: Elcodi\Component\User\Services\PasswordManager
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@router'
            - '@elcodi.event_dispatcher.password'
            - '@elcodi.generator.sha1'

    elcodi.manager.customer:
        class: Elcodi\Component\User\Services\CustomerManager
        arguments:
            - '@elcodi.event_dispatcher.user'

    elcodi.manager.admin_user:
        class: Elcodi\Component\User\Services\AdminUserManager
        arguments:
            - '@elcodi.event_dispatcher.user'

    elcodi.excel_manager.customer:
        class: Elcodi\Component\User\Services\ExcelCustomerManager
        arguments:
            - '@translator'
            - '@elcodi.money_printer'
            - '@elcodi.download_utility'