services:

    #
    # Factories
    #

    #
    # Factory for entity coupon
    #
    elcodi.factory.coupon:
        class: Elcodi\Component\Coupon\Factory\CouponFactory
        parent: elcodi.factory.abstract.purchasable
        calls:
            - [setEntityNamespace, ["%elcodi.entity.coupon.class%"]]
            - [setDateTimeFactory, ["@elcodi.factory.datetime"]]

    elcodi.factory.customer_coupon:
        class: Elcodi\Component\Coupon\Factory\CustomerCouponFactory
        parent: elcodi.factory.abstract.purchasable
        calls:
            - [setEntityNamespace, ["%elcodi.entity.customer_coupon.class%"]]
            - [setDateTimeFactory, ["@elcodi.factory.datetime"]]
