services:

    #
    # Object Managers
    #
    elcodi.object_manager.coupon:
        parent: elcodi.abstract_manager
        arguments:
            - %elcodi.entity.coupon.class%

    elcodi.object_manager.customer_coupon:
        parent: elcodi.abstract_manager
        arguments:
            - %elcodi.entity.customer_coupon.class%

    elcodi.object_manager.coupon_campaign:
        parent: elcodi.abstract_manager
        arguments:
            - %elcodi.entity.coupon_campaign.class%