services:

    #
    # Repositories
    #

    #
    # Repository for entity coupon
    #
    elcodi.repository.coupon:
        parent: elcodi.abstract_repository
        arguments:
            - %elcodi.entity.coupon.class%
    elcodi.repository.customer_coupon:
        parent: elcodi.abstract_repository
        arguments:
            - %elcodi.entity.customer_coupon.class%
    elcodi.repository.coupon_campaign:
        parent: elcodi.abstract_repository
        arguments:
            - %elcodi.entity.coupon_campaign.class%
