Elcodi\Component\User\Entity\Customer:
    type: entity
    repositoryClass: Elcodi\Component\User\Repository\CustomerRepository
    table: customer
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        phone:
            column: phone
            type: string
            length: 15
            nullable: true
        identityDocument:
            column: identity_document
            type: string
            length: 255
            nullable: true
        guest:
            column: guest
            type: boolean
        company:
            column: company
            type: boolean
        companyName:
            column: company_name
            type: string
            length: 255
            nullable: true
        vat:
            column: vat
            type: string
            length: 255
            nullable: true
        fiscalCode:
            column: fiscal_code
            type: string
            length: 255
            nullable: true
        newsletter:
            column: newsletter
            type: boolean
        extraData:
            column: extra_data
            type: json_array
            nullable: true 
        salt:
            column: salt
            type: string
            length: 255
            nullable: true
        roles:
            column: roles
            type: array
            nullable: true 

    oneToMany:
        carts:
            targetEntity: Elcodi\Component\Cart\Entity\Interfaces\CartInterface
            mappedBy: customer
            orderBy:
                createdAt: DESC
            cascade: [ "persist" ]

        orders:
            targetEntity: Elcodi\Component\Cart\Entity\Interfaces\OrderInterface
            mappedBy: customer
            orderBy:
                createdAt: DESC
            cascade: [ "persist" ]

    oneToOne:
        deliveryAddress:
            targetEntity: Elcodi\Component\Geo\Entity\Interfaces\AddressInterface
            joinColumn:
                name: delivery_address_id
                referencedColumnName: id
                nullable: true
                onDelete: "SET NULL"
            cascade: [ "persist" ]

        invoiceAddress:
            targetEntity: Elcodi\Component\Geo\Entity\Interfaces\AddressInterface
            joinColumn:
                name: invoice_address_id
                referencedColumnName: id
                nullable: true
                onDelete: "SET NULL"
            cascade: [ "persist" ]

    manyToOne:
        language:
            targetEntity: Elcodi\Component\Language\Entity\Interfaces\LanguageInterface
            joinColumn:
                name: language_iso
                referencedColumnName: iso
                nullable: true
        tax:
            targetEntity: Elcodi\Component\Tax\Entity\Interfaces\TaxInterface
            joinColumn:
                 name: tax_id
                 referencedColumnName: id
                 nullable: true
        country:
            targetEntity: Elcodi\Component\Geo\Entity\Interfaces\CountryInterface
            joinColumn:
                 name: country_id
                 referencedColumnName: id
                 nullable: true

    manyToMany:
        addresses:
            targetEntity: Elcodi\Component\Geo\Entity\Interfaces\AddressInterface
            joinTable:
                name: customer_address
                joinColumns:
                    customer_id:
                        referencedColumnName: id
                inverseJoinColumns:
                    address_id:
                        referencedColumnName: id

    lifecycleCallbacks:
            preUpdate: [loadUpdateAt]
            prePersist: [loadUpdateAt]
