Elcodi\Component\User\Entity\CustomerCategory:
    type: entity
    repositoryClass: Elcodi\Component\User\Repository\CustomerCategoryRepository
    table: customer_category
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        name:
            column: name
            type: string
            length: 255
            nullable: true
        createdAt:
            column: created_at
            type: datetime
        updatedAt:
            column: updated_at
            type: datetime
        enabled:
            column: enabled
            type: boolean
        extraData:
            column: extra_data
            type: json_array
            nullable: true
       
                
    manyToMany:
        customers:
            targetEntity: Elcodi\Component\User\Entity\Interfaces\CustomerInterface
            mappedBy: customerCategories
        #categories:
        #    targetEntity: Elcodi\Component\User\Entity\Interfaces\CustomerCategoryInterface
        #    mappedBy: customerCategories
        
    lifecycleCallbacks:
        preUpdate: [loadUpdateAt]
        prePersist: [loadUpdateAt]
