Elcodi\Component\Permissions\Entity\PermissionGroup:
    type: entity
    repositoryClass: Elcodi\Component\Permissions\Repository\PermissionGroupRepository
    table: permission_groups
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        name:
            column: name
            type: string
            nullable: true
    
    manyToOne:
        adminUser:
            targetEntity: Elcodi\Component\User\Entity\Interfaces\AdminUserInterface
            joinColumn:
                name: admin_id
                referencedColumnName: id
                nullable: true
                onDelete: "SET NULL"

    oneToMany:
        permissions:
            targetEntity: Elcodi\Component\Permissions\Entity\Interfaces\AbstractPermissionInterface
            mappedBy: permissionGroup
            cascade: [ "all", "persist" ]
            orphanRemoval: true
            fetch: EAGER
