Elcodi\Component\Coupon\Entity\Coupon:
    type: entity
    repositoryClass: Elcodi\Component\Coupon\Repository\CouponRepository
    table: coupon
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        code:
            column: code
            type: string
            length: 255
            nullable: false
            unique: true
        name:
            column: name
            type: string
            length: 255
            nullable: false
        type:
            column: type
            type: integer
            nullable: false
        enforcement:
            column: enforcement
            type: integer
            nullable: false
        priceAmount:
            column: price_amount
            type: integer
        discount:
            column: discount
            type: integer
        value:
            column: value
            type: string
            length: 255
            nullable: true
        count:
            column: count
            type: integer
            nullable: false
        countCustomer:
            column: count_customer
            type: integer
            nullable: false
        used:
            column: used
            type: integer
            nullable: false
        priority:
            column: priority
            type: integer
            nullable: false
        minimumPurchaseAmount:
            column: minimum_purchase_amount
            type: integer
            nullable: true
        stackable:
            column: stackable
            type: boolean
            nullable: false
            options:
                default: false
        validFrom:
            column: valid_from
            type: datetime
            nullable: false
        validTo:
            column: valid_to
            type: datetime
            nullable: true
        color:
            column: color
            type: string
            length: 255
            nullable: true
        freeShipping:
            column: free_shipping
            type: boolean
            nullable: true
            options:
                default: false
        createdAt:
            column: created_at
            type: datetime
            nullable: true
        updatedAt:
            column: updated_at
            type: datetime
            nullable: true
        enabled:
            column: enabled
            type: boolean
        includeCategories:
            column: include_categories
            type: integer
            nullable: true
        extraData:
            column: extra_data
            type: json_array
            nullable: true 
                
    manyToOne:
        priceCurrency:
            targetEntity: Elcodi\Component\Currency\Entity\Interfaces\CurrencyInterface
            joinColumn:
                 name: price_currency_iso
                 referencedColumnName: iso
                 nullable: true
        minimumPurchaseCurrency:
            targetEntity: Elcodi\Component\Currency\Entity\Interfaces\CurrencyInterface
            joinColumn:
                 name: minimum_purchase_currency_iso
                 referencedColumnName: iso
                 nullable: true
        couponCampaign:
            targetEntity: Elcodi\Component\Coupon\Entity\Interfaces\CouponCampaignInterface
            joinColumn:
                name: coupon_campaign_id
                referencedColumnName: id
                nullable: true
        rule:
            targetEntity: Elcodi\Component\Rule\Entity\Interfaces\RuleInterface
            fetch: EAGER
            joinColumn:
                name: rule
                referencedColumnName: id
                nullable: true
    manyToMany:
        categories:
            targetEntity: Elcodi\Component\Product\Entity\Interfaces\CategoryInterface
            inversedBy: coupons
            joinTable:
                name: coupon_category
                joinColumns:
                    coupon_id:
                        referencedColumnName: id
                        onDelete: "CASCADE"
                inverseJoinColumns:
                    category_id:
                        referencedColumnName: id
                        onDelete: "CASCADE"
        customerCategories:
            targetEntity: Elcodi\Component\User\Entity\Interfaces\CustomerCategoryInterface
            inversedBy: customers
            joinTable:
                name: customers_coupons
                joinColumns:
                    coupon_id:
                        referencedColumnName: id
                        onDelete: "CASCADE"
                inverseJoinColumns:
                    customer_category_id:
                        referencedColumnName: id
                        onDelete: "CASCADE"

    lifecycleCallbacks:
        preUpdate: [loadUpdateAt]
        prePersist: [loadUpdateAt]
