Elcodi\Component\Cart\Entity\Cart:
    type: entity
    repositoryClass: Elcodi\Component\Cart\Repository\CartRepository
    table: cart
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        ordered:
            column: ordered
            type: boolean
            nullable: false
        ifNotOrderedUseThis:
            column: if_not_ordered_use_this
            type: boolean
            nullable: true
        shippingMethod:
            column: shipping_method
            type: string
            nullable: true
        taxAmount:
            column: tax_amount
            type: integer
            nullable: true
        createdAt:
            column: created_at
            type: datetime
        updatedAt:
            column: updated_at
            type: datetime
        extraData:
            column: extra_data
            type: json_array
            nullable: true 
            
    oneToOne:
        order:
            targetEntity: Elcodi\Component\Cart\Entity\Interfaces\OrderInterface
            mappedBy: cart

    manyToOne:
        customer:
            targetEntity: Elcodi\Component\User\Entity\Interfaces\CustomerInterface
            inversedBy: carts
            joinColumn:
                name: customer_id
                referencedColumnName: id
                nullable: true
                onDelete: "SET NULL"

        deliveryAddress:
            targetEntity: Elcodi\Component\Geo\Entity\Interfaces\AddressInterface
            joinColumn:
                name: delivery_address_id
                referencedColumnName: id
                nullable: true

        billingAddress:
            targetEntity: Elcodi\Component\Geo\Entity\Interfaces\AddressInterface
            joinColumn:
                name: billing_address_id
                referencedColumnName: id
                nullable: true
        taxCurrency:
            targetEntity: Elcodi\Component\Currency\Entity\Interfaces\CurrencyInterface
            joinColumn:
                 name: tax_currency_iso
                 referencedColumnName: iso
                 nullable: true

    oneToMany:
        cartLines:
            targetEntity: Elcodi\Component\Cart\Entity\Interfaces\CartLineInterface
            mappedBy: cart
            cascade: [ "all" ]
            orphanRemoval: true
            fetch: EAGER

    lifecycleCallbacks:
        preUpdate: [loadUpdateAt]
        prePersist: [loadUpdateAt]
