services:
    #
    # Directors
    #
    elcodi.director.permission_group:
        class: Elcodi\Component\Core\Services\ObjectDirector
        lazy: true
        arguments:
            - '@elcodi.object_manager.permission_group'
            - '@elcodi.repository.permission_group'
            - '@elcodi.factory.permission_group'